package fptu.summer.model;
// Generated Jun 3, 2018 2:37:40 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * LastViewNotification generated by hbm2java
 */
public class LastViewNotification implements java.io.Serializable {

    private int userId;
    private Date lastView;

    public LastViewNotification() {
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Date getLastView() {
        return this.lastView;
    }

    public void setLastView(Date lastView) {
        this.lastView = lastView;
    }

}
