package fptu.summer.model;
// Generated Jun 3, 2018 2:37:40 PM by Hibernate Tools 4.3.1

/**
 * SystemNotification generated by hbm2java
 */
public class SystemNotification implements java.io.Serializable {

    private long notificationId;
    private Notification notification;
    private User user;
    private String note;
    private int status;

    public SystemNotification() {
    }

    public SystemNotification(Notification notification, int status) {
        this.notification = notification;
        this.status = status;
    }

    public SystemNotification(Notification notification, User user, String note, int status) {
        this.notification = notification;
        this.user = user;
        this.note = note;
        this.status = status;
    }

    public long getNotificationId() {
        return this.notificationId;
    }

    public void setNotificationId(long notificationId) {
        this.notificationId = notificationId;
    }

    public Notification getNotification() {
        return this.notification;
    }

    public void setNotification(Notification notification) {
        this.notification = notification;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

}
