package fptu.summer.model;
// Generated Jun 3, 2018 2:37:40 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import fptu.summer.model.enumeration.TransactionStatus;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

    @JsonProperty("local_id")
    private Long localId;
    @JsonProperty("server_id")
    private Long id;
    private Ledger ledger;
    @JsonIgnore
    private Stakeholder debtor;
    @JsonIgnore
    private Stakeholder creditor;
    private TransactionGroup transactionGroup;
    private double balance;
    private String note;
    private boolean countedOnReport = true;
    private Date insertDate;
    private Date lastUpdate;
    private int status = TransactionStatus.ENABLE.getStatus();
    private Date date;

    public Transaction() {
    }

    public Long getLocalId() {
        return localId;
    }

    public void setLocalId(Long localId) {
        this.localId = localId;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Ledger getLedger() {
        return this.ledger;
    }

    public void setLedger(Ledger ledger) {
        this.ledger = ledger;
    }

    public TransactionGroup getTransactionGroup() {
        return this.transactionGroup;
    }

    public void setTransactionGroup(TransactionGroup transactionGroup) {
        this.transactionGroup = transactionGroup;
    }

    public double getBalance() {
        return this.balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public boolean isCountedOnReport() {
        return this.countedOnReport;
    }

    public void setCountedOnReport(boolean countedOnReport) {
        this.countedOnReport = countedOnReport;
    }

    public Date getInsertDate() {
        return this.insertDate;
    }

    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Stakeholder getDebtor() {
        return debtor;
    }

    public void setDebtor(Stakeholder debtor) {
        this.debtor = debtor;
    }

    public Stakeholder getCreditor() {
        return creditor;
    }

    public void setCreditor(Stakeholder creditor) {
        this.creditor = creditor;
    }

}
