package fptu.summer.model;
// Generated Jun 3, 2018 2:37:40 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * UserSetting generated by hbm2java
 */
public class UserSetting implements java.io.Serializable {

    private int userId;
    private User user;
    private int monthStartDate = 1;
    private String timeFormat = "dd/mm/yyyy";
    private Date lastUpdate = new Date();

    public UserSetting() {
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getMonthStartDate() {
        return this.monthStartDate;
    }

    public void setMonthStartDate(int monthStartDate) {
        this.monthStartDate = monthStartDate;
    }

    public String getTimeFormat() {
        return this.timeFormat;
    }

    public void setTimeFormat(String timeFormat) {
        this.timeFormat = timeFormat;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
