package fptu.summer.model.id;
// Generated Jun 3, 2018 2:37:40 PM by Hibernate Tools 4.3.1

/**
 * UserNotificationId generated by hbm2java
 */
public class UserNotificationId implements java.io.Serializable {

    private int userId;
    private long notificationId;

    public UserNotificationId() {
    }

    public UserNotificationId(int userId, long notificationId) {
        this.userId = userId;
        this.notificationId = notificationId;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public long getNotificationId() {
        return this.notificationId;
    }

    public void setNotificationId(long notificationId) {
        this.notificationId = notificationId;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof UserNotificationId)) {
            return false;
        }
        UserNotificationId castOther = (UserNotificationId) other;

        return (this.getUserId() == castOther.getUserId())
                && (this.getNotificationId() == castOther.getNotificationId());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserId();
        result = 37 * result + (int) this.getNotificationId();
        return result;
    }

}
